#!/bin/bash -e

root_dir=$(dirname $BASH_SOURCE[0])
will_exit=0

#
# First, check all the mandatory environment variables
#
for variable in \
  NEW_RELIC_LICENSE_KEY \
  $(cat "$root_dir/required-variables.txt")
do
  eval target=\$$variable
  if [ -z "${target}" ]; then
    echo "Must set $variable environment variable!"
    will_exit=1
  fi
done

if [ 0 -ne $will_exit ]; then
  echo "Exiting"
  exit $will_exit
fi

#
# Then create the config dir if needed and write the configs
#
mkdir -p "$root_dir/config/"

cat > "$root_dir/config/newrelic_plugin.yml" <<EOF_YAML
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: '${NEW_RELIC_LICENSE_KEY}'
EOF_YAML

[ "debug" == "${NEW_RELIC_LOG_LEVEL}" ] && cat >> "$root_dir/config/newrelic_plugin.yml" <<EOF_YAML
  verbose: 1
EOF_YAML

# Changing the endpoint is used internally at New Relic for development and testing
[ -z "${NEW_RELIC_ENDPOINT}" ] || cat >> "$root_dir/config/newrelic_plugin.yml" <<EOF_YAML
  endpoint: '${NEW_RELIC_ENDPOINT}'
EOF_YAML

# Now write out the specific config for this plugin
cat >> "$root_dir/config/newrelic_plugin.yml" <<EOF_YAML
#
# Agent Configuration:
#
agents:
  f5:
    -
EOF_YAML

for variable in $(env | egrep ^PLUGIN_ | cut -f1 -d\=); do
  eval value=\$$variable
  eval key=$(echo $variable | cut -f2- -d\_ | tr A-Z a-z)
  cat >> "$root_dir/config/newrelic_plugin.yml" <<EOF_YAML
      ${key}: '${value}'
EOF_YAML
done
