#!/bin/bash -e

root_dir=$(dirname $BASH_SOURCE[0])
will_exit=0

#
# First, check all the mandatory environment variables
#
for variable in \
  NEW_RELIC_LICENSE_KEY NEW_RELIC_LOG_LEVEL \
  $(cat "$root_dir/required-variables.txt")
do
  eval target=\$$variable
  if [ -z "${target}" ]; then
    echo "Must set $variable environment variable!"
    will_exit=1
  fi
done

if [ 0 -ne $will_exit ]; then
  echo "Exiting"
  exit $will_exit
fi

#
# Then create the config dir if needed and write the configs
#
mkdir -p "$root_dir/config/"

cat > "$root_dir/config/newrelic.json" <<EOF_JSON
{
  "license_key": "${NEW_RELIC_LICENSE_KEY}",
EOF_JSON

# Changing the endpoint is used internally at New Relic for development and testing
[ -z "${NEW_RELIC_ENDPOINT}" ] || cat >> "$root_dir/config/newrelic.json" <<EOF_JSON
  "endpoint": "${NEW_RELIC_ENDPOINT}",
EOF_JSON

cat >> "$root_dir/config/newrelic.json" <<EOF_JSON
  "log_level": "${NEW_RELIC_LOG_LEVEL}",
  "log_file_name": "null",
  "log_file_path": "/dev"
}
EOF_JSON

# Now write out the specific config for this plugin
cat > "$root_dir/config/plugin.json" <<EOF_JSON
{
  "agents": [
    {
EOF_JSON

for variable in $(env | egrep ^PLUGIN_ | cut -f1 -d\=); do
  eval value=\$$variable
  eval key=$(echo $variable | cut -f2- -d\_ | tr A-Z a-z)
  cat >> "$root_dir/config/plugin.json" <<EOF_JSON
      "${key}": "${value}",
EOF_JSON
done

cat >> "$root_dir/config/plugin.json" <<EOF_JSON
    }
  ]
}
EOF_JSON
